#yaml-language-server: $schema=../plugin.schema.json
- id: kill-pods
  config:
    namespace_pattern: ^redhat-ods-monitoring$
    label_selector: deployment=prometheus
    kill: 1
- id: wait-for-pods
  config:
    namespace_pattern: ^redhat-ods-monitoring$
    label_selector: deployment=prometheus
    count: 1