#yaml-language-server: $schema=../plugin.schema.json
- id: kill-pods
  config:
    namespace_pattern: ^redhat-ods-monitoring$
    label_selector: app.kubernetes.io/name=rhods-prometheus-operator
    kill: 1
    timeout: 120
- id: wait-for-pods
  config:
    namespace_pattern: ^redhat-ods-monitoring$
    label_selector: app.kubernetes.io/name=rhods-prometheus-operator
    count: 1